defmodule UltraLogLog.EncodingTest do
  @moduledoc """
  Bit-exact cross-check of `UltraLogLog.Encoding.encode/2` against the
  Hash4j v0.17.0 reference (the version pinned by the paper
  reproduction repository). Vectors live in `test/fixtures/encoding_vectors.json`
  and are regenerated by `test/fixtures/java/generate.sh`.

  The fixture covers:

    * random hashes at p ∈ {3, 8, 10, 12, 14, 26}, including the
      precision-range bounds (`MIN_P = 3`, `MAX_P = 26`),
    * the all-zero tail (encode saturates to `pack(1 <<< 63)`) at the
      same precision set,
    * a leading-1 sweep across every bit position 63..0, repeated for
      p ∈ {3, 14, 26} — exercises the saturated-NLZ branch for
      positions k < p as well as the natural-hash branch for k ≥ p.
  """

  use ExUnit.Case, async: true

  alias UltraLogLog.Encoding

  @vectors_path Path.join([__DIR__, "fixtures", "encoding_vectors.json"])

  test "encode/2 matches Hash4j ground truth for every fixture vector" do
    assert File.exists?(@vectors_path),
           "missing #{@vectors_path} — regenerate with test/fixtures/java/generate.sh"

    %{"vectors" => vectors} = @vectors_path |> File.read!() |> JSON.decode!()

    refute vectors == [], "fixture file produced no vectors"

    mismatches =
      for %{"tail" => tail_str, "p" => p, "expected" => expected} <- vectors,
          tail = String.to_integer(tail_str),
          got = Encoding.encode(tail, p),
          got != expected do
        %{tail: tail, p: p, got: got, expected: expected}
      end

    assert mismatches == [],
           "Hash4j encoding mismatch on #{length(mismatches)} of " <>
             "#{length(vectors)} vectors. First 3: " <>
             inspect(Enum.take(mismatches, 3), pretty: true)
  end
end
