/*
 * Hash4j-derived test fixtures for the Elixir UltraLogLog port.
 *
 * Emits two kinds of artifact into the mounted /out directory (which the
 * surrounding generate.sh binds to test/fixtures/ on the host):
 *
 *   1. Register snapshots for the reference-vectors test:
 *      ull_p{p}_n{n}.bin  — raw 2^p register bytes
 *      ull_n{n}.seeds     — the u64 hashes inserted, one per line, in
 *                            insertion order (cumulative; shared across
 *                            precisions since the RNG seed is fixed)
 *      for p in {8, 10, 12, 14} and n in {100, 1k, 10k, 100k}.
 *
 *   2. Encoding vectors for the unit test:
 *      encoding_vectors.json — a JSON document with (tail, p, expected_byte)
 *                              triples covering random hashes, the all-zero
 *                              tail, and a single bit set in every position
 *                              63..0 (for p=10).
 *
 *   3. FGRA estimator ground truth for the spot-check test:
 *      fgra_estimates.json   — for each (p, n) pair under (1), the value
 *                              returned by Hash4j's OPTIMAL_FGRA_ESTIMATOR
 *                              (the only FGRA implementation Hash4j ships;
 *                              see UltraLogLog.java in v0.17.0). Computed
 *                              from the same register state already dumped
 *                              in (1), so the spot-check exercises the
 *                              estimator independently of the encoding.
 *
 * Hash seeds are a fixed SplittableRandom(0xC0FFEEL) sequence so the
 * fixtures are deterministic across runs.
 *
 * Hash4j ground truth: distinctcount.UltraLogLog. The pack/unpack scheme
 * the Elixir port reproduces lives in that file (lines 331-339).
 */
import com.dynatrace.hash4j.distinctcount.UltraLogLog;

import java.io.BufferedWriter;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.SplittableRandom;

public class GenerateFixtures {

    private static final long INSERT_SEED = 0xC0FFEEL;
    private static final long VECTOR_SEED = 0xBA0BABL;

    private static final int[] PRECISIONS = {8, 10, 12, 14};
    private static final int[] CHECKPOINTS = {100, 1_000, 10_000, 100_000};

    // For encoding-vector tests: includes the precision-range bounds
    // (3 = MIN_P, 26 = MAX_P) plus a mid value for sweep coverage.
    private static final int[] VECTOR_PRECISIONS = {3, 8, 10, 12, 14, 26};
    private static final int[] SWEEP_PRECISIONS = {3, 14, 26};

    public static void main(String[] args) throws Exception {
        String outDir = args.length > 0 ? args[0] : "/out";
        Files.createDirectories(Paths.get(outDir));

        // Seeds first (precision-independent), then register dumps per p.
        writeSharedSeeds(outDir);
        System.out.println("wrote seeds");

        // (p, n) -> Hash4j OPTIMAL_FGRA_ESTIMATOR estimate, accumulated as
        // we sweep precisions so the JSON groups by precision in order.
        StringBuilder fgraJson = new StringBuilder();
        fgraJson.append("{\n");
        fgraJson.append("  \"_comment\": \"Generated by GenerateFixtures.java against Hash4j v0.17.0. ");
        fgraJson.append("'estimate' is UltraLogLog.OPTIMAL_FGRA_ESTIMATOR applied to the register state at ");
        fgraJson.append("ull_p{p}_n{n}.bin. The Elixir port's FGRA estimator must agree within 0.1% relative.\",\n");
        fgraJson.append("  \"hash4j_version\": \"0.17.0\",\n");
        fgraJson.append("  \"estimator\": \"OPTIMAL_FGRA_ESTIMATOR\",\n");
        fgraJson.append("  \"vectors\": [");
        boolean firstFgra = true;

        for (int p : PRECISIONS) {
            firstFgra = writeRegisterDumpsForPrecision(outDir, p, fgraJson, firstFgra);
            System.out.printf(Locale.ROOT, "wrote register dumps for p=%d%n", p);
        }

        fgraJson.append("\n  ]\n}\n");
        Files.writeString(Paths.get(outDir, "fgra_estimates.json"), fgraJson.toString());
        System.out.println("wrote fgra_estimates.json");

        writeEncodingVectors(outDir);
        System.out.println("wrote encoding_vectors.json");
    }

    private static void writeSharedSeeds(String outDir) throws Exception {
        SplittableRandom rng = new SplittableRandom(INSERT_SEED);
        List<Long> cumulativeSeeds = new ArrayList<>();
        int target = 0;
        for (int n : CHECKPOINTS) {
            int delta = n - target;
            for (int i = 0; i < delta; i++) {
                cumulativeSeeds.add(rng.nextLong());
            }
            target = n;

            Path seedsPath = Paths.get(outDir, String.format(Locale.ROOT, "ull_n%d.seeds", n));
            try (BufferedWriter w = Files.newBufferedWriter(seedsPath)) {
                for (long h : cumulativeSeeds) {
                    w.write(Long.toUnsignedString(h));
                    w.newLine();
                }
            }
        }
    }

    private static boolean writeRegisterDumpsForPrecision(
            String outDir, int p, StringBuilder fgraJson, boolean firstFgra) throws Exception {
        UltraLogLog ull = UltraLogLog.create(p);
        SplittableRandom rng = new SplittableRandom(INSERT_SEED);
        int target = 0;
        for (int n : CHECKPOINTS) {
            int delta = n - target;
            for (int i = 0; i < delta; i++) {
                ull.add(rng.nextLong());
            }
            target = n;
            Path binPath = Paths.get(outDir, String.format(Locale.ROOT, "ull_p%d_n%d.bin", p, n));
            Files.write(binPath, ull.getState());

            // Snapshot the FGRA estimate at the same checkpoint, against the
            // same in-memory sketch we just dumped to disk.
            double estimate = ull.getDistinctCountEstimate(UltraLogLog.OPTIMAL_FGRA_ESTIMATOR);
            if (!firstFgra) fgraJson.append(",");
            fgraJson.append("\n    ");
            fgraJson.append(String.format(
                    Locale.ROOT,
                    "{\"p\": %d, \"n\": %d, \"estimate\": %s}",
                    p, n, formatDouble(estimate)));
            firstFgra = false;
        }
        return firstFgra;
    }

    // Use the canonical IEEE-754 round-trippable repr (Java Double.toString)
    // so the JSON preserves the exact double value Hash4j produced. The
    // Elixir test re-parses this string into a float and compares with a
    // 0.1% relative tolerance, so the formatting only matters insofar as
    // it doesn't lose precision.
    private static String formatDouble(double d) {
        return Double.toString(d);
    }

    private static void writeEncodingVectors(String outDir) throws Exception {
        StringBuilder sb = new StringBuilder();
        sb.append("{\n");
        sb.append("  \"_comment\": \"Generated by GenerateFixtures.java against Hash4j. ");
        sb.append("'tail' is the 64-bit hash with the top p bits already shifted out, as an unsigned decimal string. ");
        sb.append("'expected' is the byte value (0..255) of encode(tail, p).\",\n");
        sb.append("  \"vectors\": [\n");

        boolean first = true;

        // (a) Random hashes × precisions (including bounds {3, 26}).
        SplittableRandom rng = new SplittableRandom(VECTOR_SEED);
        long[] randomHashes = new long[4];
        for (int i = 0; i < randomHashes.length; i++) {
            randomHashes[i] = rng.nextLong();
        }
        for (long h : randomHashes) {
            for (int p : VECTOR_PRECISIONS) {
                long tail = h << p;
                int expected = encodeByteFor(h, p);
                appendVector(sb, tail, p, expected, first);
                first = false;
            }
        }

        // (b) All-zero tail per precision (saturates to pack(1 << 63)).
        for (int p : VECTOR_PRECISIONS) {
            long hash = 1L << 63;  // top bit set; bottom 64-p bits zero
            long tail = hash << p; // = 0 for any p ≥ 1
            int expected = encodeByteFor(hash, p);
            appendVector(sb, tail, p, expected, first);
            first = false;
        }

        // (c) Tail with leading 1 in every position 63..0, for each of
        //     the precision-range bounds p ∈ {3, 14, 26}. For positions
        //     k < p the tail is unreachable from any natural hash, but
        //     encode/2 still has a defined output — and that output
        //     coincides with encode(0, p), which we obtain via hash = 0
        //     through the public API.
        for (int p : SWEEP_PRECISIONS) {
            for (int k = 63; k >= 0; k--) {
                long tail = 1L << k;
                long hash = (k >= p) ? (1L << (k - p)) : 0L;
                int expected = encodeByteFor(hash, p);
                appendVector(sb, tail, p, expected, first);
                first = false;
            }
        }

        sb.append("\n  ]\n}\n");
        Files.writeString(Paths.get(outDir, "encoding_vectors.json"), sb.toString());
    }

    private static int encodeByteFor(long hash, int p) {
        UltraLogLog probe = UltraLogLog.create(p);
        probe.add(hash);
        int idx = (int) (hash >>> (64 - p));
        return probe.getState()[idx] & 0xFF;
    }

    private static void appendVector(StringBuilder sb, long tail, int p, int expected, boolean first) {
        if (!first) sb.append(",\n");
        sb.append(String.format(
                Locale.ROOT,
                "    {\"tail\": \"%s\", \"p\": %d, \"expected\": %d}",
                Long.toUnsignedString(tail), p, expected));
    }
}
